use_frameworks!

target 'DownloadingFileAsset_Example' do
  pod 'DownloadingFileAsset', :path => '../'

  target 'DownloadingFileAsset_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
